# ©2022 TypeSoft s. r. o. All rights reserved.

name: ui_kit
description: Reusable UI elements in Flutter (mostly widgets). Removes code duplication throughout projects.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  master_kit:
    path: ../master_kit
  flutter_portal: ^1.1.4
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.6
  gradient_borders: ^1.0.0
  material_color_utilities: any # version pinned by flutter
  rxdart: ^0.27.7
  collection: ^1.18.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
